FROM container-registry.oracle.com/java/openjdk:23 as prod

RUN dnf update -y --refresh \
  && dnf install -y jq \
  && dnf clean all -y

ARG api=https://api.papermc.io \
  && project=velocity \
  && version=3.4.0-SNAPSHOT

RUN build=$(curl -fsSL ${api}/v2/projects/${project}/versions/${version}/builds -H 'Accept: application/json' | jq '.builds [-1].build') \
  && url=${api}/v2/projects/${project}/versions/${version}/builds/${build}/downloads/velocity-${version}-${build}.jar \
  && curl -fsSL ${url} -o /bin/velocity.jar

RUN mkdir -p /velocity

WORKDIR /velocity

COPY ./entrypoint.sh /bin/entrypoint.sh

ENTRYPOINT ["sh", "/bin/entrypoint.sh"]
